// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type Query struct {
	Queryid          int32
	Querydescription string
	Query            string
}

type QueryParameter struct {
	Parameterid   int32
	Queryid       int32
	Parametername string
	Datatype      string
	Ordered       int32
}
